### ISSUE TITLE
Front Page Content section not visible after update?!

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1097]
https://wordpress.org/support/topic/front-page-customizer-section/#post-9350454

**Comment by eri-trabiccolo** [comment]
is this related to #1096 in a way?
might the czr_fn_is_real_home() produce this?

I cannot reproduce these issues though

**Comment by eri-trabiccolo** [comment]
The featured pages issue was introduced by me,
the code to parse the fp img (using the ampersand on an array field) seems to not work with php5.3
no errors or warning but no fp shown

**Comment by hardycyr** [comment]
Hello,

I am also having the same issue, The Front Page Content section is not displayed. When I checked the HTML, I can see that the style="display: none" is set for that section.
I am using WP 4.8.1 with Customizr 4.0.5 and PHP 7.1.
Is there any workaround to access this section so that I can continue my developments?
Thanks a lot and best regards,

**Comment by Steelydan69** [comment]
Hi,
Same Problem for me as for hardycyr: WP 4.8.1, Customizr 4.0.5, PHP 7.1. A solution would be very much appreciated. Thanks a lot and have a nice day.
