### ISSUE TITLE
Images caption are not well handled when printed in the archive header

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1116]
> I have a “visual” issue : when I add a photo with a caption in the archive of a category, the pseudo html appears instead of a proper visua ltreatment. any idea to correct this problem ?
> 
> Here an exemple : http://www.societe-mycologique-poitou.org/category/inventaire-mycologique/myxomycetes/
> 
> Thanks for your help.

**Comment by eri-trabiccolo** [comment]
I would close this because, the cat description are not really meant to contain the caption shortcode.
To add an image with a caption you basically have to "hardcode" it, in the simple cat description textarea field.
There are plugins that enhance that textarea with a tinymce alike editor.
Hence applying the `do_shortcode` callback to the relevant filters.
