### ISSUE TITLE
Customizer - Social links in header notice issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1118]
https://github.com/presscustomizr/customizr/blob/v4.0.4/core/core-settings-map.php#L546

Not sure when and why this notice as been added but
1) should not be applied to the classic style
2) the link is totally useless as a) the topbar display control in the modern is just above this option b) the topbar display in the classical style doesn't exist

reported here:
https://secure.helpscout.net/conversation/406698169/30602/?folderId=607709

**Comment by ghost** [comment]
yep good catch.
Quick note tough :  In modern style, these notice and link are useful when customizing the socials in Global Settings > Social links (=> the ubiquity of this control ). Because you might want to check the socials in header option, and not see the social icons appear if your topbar is disabled.

The notice should only be displayed in modern.

The notice should say smthg like : "check the topbar option here or LINK Jump ..."

**Comment by eri-trabiccolo** [comment]
The ubiquity in this case then creates complexity we don't need, I think...
Would be easier, then, just don't display the socials in header control when the topbar display option is off, and only for the modern style. No?!

**Comment by ghost** [comment]
nope because users might not even know this option exists if we do that

**Comment by eri-trabiccolo** [comment]
I see... ;)
