### ISSUE TITLE
RTL : search icon not properly left aligned on full screen search

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1159]
![search_rtl_problem](https://user-images.githubusercontent.com/3038156/30002668-ac5fb678-90af-11e7-8972-59c8ae18cc43.jpg)

**Comment by JTS-IL** [comment]
Where is this search located?
I cannot find it in my sites to check it :-(

**Comment by eri-trabiccolo** [comment]
@Nikeo 
cannot reproduce it, can you?
Link to the bugged site?

@JTS-IL 
that search is in the modern style ;)

**Comment by ghost** [comment]
@JTS-IL  since the latest version you can select 2 different style for the theme : http://docs.presscustomizr.com/article/119-customizr-theme-options-advanced-options#style

@eri-trabiccolo http://etsyplus.co.il/ but I did not investigate further if it was a plugin conflict for the moment.

**Comment by JTS-IL** [comment]
OK
I will check it soon!

יעקב

**Sent from my mobile**
www.glezer.co.il

On 4 בספט׳ 2017, at 10:54, Nicolas Guillaume (@nikeo on wp.org) <notifications@github.com> wrote:

@JTS-IL since the latest version you can select 2 different style for the theme : http://docs.presscustomizr.com/article/119-customizr-theme-options-advanced-options#style

@eri-trabiccolo http://etsyplus.co.il/

**Comment by eri-trabiccolo** [comment]
@Nikeo 
Ok it seems I'm able to reproduce it. It happens only when loading the minified rtl CSS.
