### ISSUE TITLE
Galleries : the thumbnail should use a larger image size in most of the case

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1165]
150x150 will look pixelized in most of the cases

https://demo.presscustomizr.com/gallery/

@eri-trabiccolo any simple way to fix this ?

**Comment by eri-trabiccolo** [comment]
The thumbnail size it's an user choice.
What we do is to fit the image's width to the grid item's width (design choice), which is defined by the columns (user choice).

Alternatively we could set the width to auto
<img width="662" alt="gallery-img" src="https://user-images.githubusercontent.com/7689242/30208669-d7581300-9494-11e7-95fb-546c4d644a65.png">

At that point the "problem" would be the action link placement, and at this point I would rather remove it.

p.s.
consider also that the srcset, when available, is always printed for the galleries. For example in the link 
 you pasted above I don't see pixelated images because the current srcs loaded are 300x300

**Comment by eri-trabiccolo** [comment]
Ah, sorry, of course you can try with a different img size than the one the user chose, maybe tying this to the number of selected columns.
https://github.com/presscustomizr/customizr/blob/dev/core/front/utils/class-content-gallery.php#L40

**Comment by ghost** [comment]
thank you for this first feedback, I'll follow up later today.

**Comment by ghost** [comment]
technical specification => force the size attribute to a max-width: as a function of the number of columns
use a filter add / remove before and after the gallery

**Comment by ghost** [comment]
https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/
