### ISSUE TITLE
slider creation : some input fields may sometimes not be written in db when saving ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1168]
> Hi i'm developing a site and am integrating sliders in some pages.
> On this page:
> https://www.culturart-carraro.ch/kunst-themenkurse/
> 
> I made a mistake with the displayed text, after the slider iamge titled 'Themenkurs Frauen in der Kunst, Berthe Morisot, Kornfeld, 1875' the next image has as title '....' which is wrong.
> 
> I tried several times to replace this text in the appropriate field with the correct text. After updating the image, (top right button under the image desription), the newly inserted text is gone and the original text displays.
> 
> Looks as if the update does not read the input field properly, and thus does not update the Database with the corrected value?
> 
> Would appreciate if you can correct that!
> 
> Thank you!
> 
> Rolf

**Comment by eri-trabiccolo** [comment]
Yes, I see.
That's an old issue that affected the featured pages too **in front**, and regards the way the text is truncated.
test strings: (80 chars is the slide's title limit)
- "Themenkurs Architektur, Maurice Dufrene, Planung Galleries Lafayette, Expo ParisA" (no spaces after the 80char which is the "s" of Paris) produces => ...
- "Themenkurs Architektur, Maurice Dufrene, Planung Galleries Lafayette, Expo Paris" (80 chars) produces => Themenkurs Architektur, Maurice Dufrene, Planung Galleries Lafayette, Expo Paris ...
- "Themenkurs Architektur, Maurice Dufrene, Planung Galleries Lafayette, Expo ParisABC" produces
"Themenkurs Architektur, Maurice Dufrene, Planung Galleries Lafayette, Expo Paris ..."

EDIT:
it still affects the fp, was fixed in FPU only
