### ISSUE TITLE
Bootstrap 4 released => let's update our scss + templates

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1176]

**Comment by eri-trabiccolo** [comment]
From a preliminary look at the diff there are few things changed.
One of them is minor, and we were aware of: the drop for some old browsers (-webkit), that will result in a smaller CSS size (less prefixed properties).
But there are also some class changes that I need to check.

I cannot do this right now but I would be able to do it by the end of tomorrow.

**Comment by ghost** [comment]
ok. Let me know what you find.
I'm planning to release a version of the free and pro theme today. This will be part of the next one

**Comment by eri-trabiccolo** [comment]
Yeah, it might take a while as they totally changed the gruntfile.js and package.json
So I have to work on a way to build our min dist

**Comment by ghost** [comment]
OK. So if you don't mind, let's postpone the bootstrap update to next month.
Instead, let's focus on those two short term devs / docs

- https://github.com/presscustomizr/customizr/issues/1140
- https://github.com/presscustomizr/pro-bundle/issues/91

Let me know if this can fit in your planning ?

**Comment by Nikeo** [comment]
mm wait, I think that the header is too big

**Comment by eri-trabiccolo** [comment]
ok,
but remember that I won't be available tomorrow.

**Comment by ghost** [comment]
ok, this can be done by next Monday / Tuesday.
Not a problem.

**Comment by ghost** [comment]
Let's postpone those compat check when Bootstrap offical V4 will be released. Hopefully in early 2018.

**Comment by ghost** [comment]
v4.0 is officialy released
https://blog.getbootstrap.com/
Let's update our code

@eri-trabiccolo I propose that you make a preliminary analysis of what needs to be done and then we validate the specs together this week when you're ready.

**Comment by eri-trabiccolo** [comment]
Custom version build:
https://github.com/presscustomizr/bootstrap-light/tree/customizr-bv4

PRs:
customizr: https://github.com/presscustomizr/customizr/pull/1467
pro-bundle: https://github.com/presscustomizr/pro-bundle/pull/142

**Comment by eri-trabiccolo** [comment]
## Major changes:
- B4 drops all `transition` property prefixes for pretty old browsers.
- since we use a custom classes/js for the `collapse` we don't include anymore the b4 transitions scss part -> treated in https://github.com/presscustomizr/customizr/pull/1467/files#diff-1f9cba6b3b49542d00f2d50f826bb87bR186
- we also use custom menu `dropdown` + snake (b4 uses a jquery plugin named popper to place the dropdowns), hence we don't include anymore the b4 dropdowns scss part -> treated (only what we actually use) in: https://github.com/presscustomizr/customizr/pull/1467/files#diff-2bb89d208cf214f5838b44cd24e4c4baL123
- b4 drops all the `hidden-*` classes (used for elements visibility in different viewports) in favor of a more mobile first paradigm. An explanation of this change can be found here:
https://github.com/presscustomizr/customizr/pull/1467/files#diff-45d305d168208bef3cdf2507550d3204R168
(ops, the Imp:... line should be removed from that comment :D )

The **latter** is the only change that actually needed an intervention on the templates (models).
Child-theme users that overridden the following templates should update them:
- templates/parts/content/singular/authors/author_info.php
- templates/parts/header.php
- templates/parts/header/parts/sidenav.php
- templates/parts/header/topbar_wrapper.php


## To discuss:
Maybe finally integrate b4 sources in the theme and adapt our building process getting inspiration from the b4 one.
