### ISSUE TITLE
header dark skin : hamburger too dark on hover => becomes almost invisible

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1200]
http://www.hrtam.com/hr-talent/

## On Hover
![after](https://user-images.githubusercontent.com/3038156/31214940-d4364f1a-a9ad-11e7-9b48-851c5fd007c2.png)

**Comment by eri-trabiccolo** [comment]
I see,
this is probably due to a change we made a long time ago on the scss $grey_light color variable.

That hover color (which is the same for the cart icon btw) is always $grey_light = 777 hex (it's not derived by the foreground or background color, which is bad).

Anyway when I did the custom header skin stuff I addressed this invariability and set that on hover value to the foreground color (in the header skin css is called primary-color) with an alpha of 0.7 . [ **N.B.** this is valid only for the custom header skin. ]
Probably 0.7 is too small, 0.6 would be better.

You can test the custom header skin and if you think those values are fine we can apply them to the basic light and dark header skin too.
