### ISSUE TITLE
Shall the default layout be set to no sidebars instead of left ( for global, post and pages ) ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1203]
Because I see more and more websites not using any widgets and leaving the sidebar simply empty...
example : http://aptpuo.jungle.ca/2017/07/21/be-aware-of-job-posting-changes/

**Comment by eri-trabiccolo** [comment]
Might be the case,
though I'm not sure isn't a choice: that site pages have a layout without sidebars (not default).
But might even be set for those specific pages ....

Anyway, if it happens more with the ms, might be due to the missing helpblocks that at least tell the user "Hey you can set widgets here" implying: "hey, there's a sidebar here..."

**Comment by ghost** [comment]
yep, I thought about this too. You are right, let's first implement the helpblock.

**Comment by eri-trabiccolo** [comment]
I didn't mean that! I was just remembering those days when we wanted to be sidebars...
