### ISSUE TITLE
Dev: bulleted and numbered lists formatting commit messed up tag buttons alignment

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1228]
Commit: https://github.com/presscustomizr/customizr/commit/c9afd6c8ce6209b060fd6b7976cb6e005c7c897e
impact:
<img width="647" alt="2017-10-18_9-37-07" src="https://user-images.githubusercontent.com/7689242/31706064-f5f10494-b3e7-11e7-8c07-2bac24c4c541.png">

**Comment by eri-trabiccolo** [comment]
Actually this line:
https://github.com/presscustomizr/customizr/commit/c9afd6c8ce6209b060fd6b7976cb6e005c7c897e#diff-e5765f480c24b77671e029b369cd90c3R7198
impacts on the nav__utils li (like the search)

**Comment by eri-trabiccolo** [comment]
and on the slider bullets too see:
![2017-10-18_16-37-54](https://user-images.githubusercontent.com/3038156/31724840-108172b8-b423-11e7-8e5a-0efaa45d5495.jpg)

from: https://github.com/presscustomizr/customizr/issues/1230

**Comment by eri-trabiccolo** [comment]
and the comments tabs:
<img width="504" alt="2017-10-24_23-16-33" src="https://user-images.githubusercontent.com/7689242/31968476-87613876-b911-11e7-8b6c-f67439fe16f5.png">

**Comment by ghost** [comment]
( copy from comments in commit https://github.com/presscustomizr/customizr/commit/d7e5b507254c53cd3f895f4ddf7a663dc3165445 )

fix : (partially fixes #1228) the ul / ol issue introduced in commit c9afd6c. The ul, ol rules are now narrowed down to .tc-content-inner.

But this does not fix the problems of blocks printed inside tc-content-inner > footer like the tag cloud.
This would need a structural change in the templates :
- content\singular\post_content.php
- content\singular\page_content.php
- content\singular\attachment_image_content.php

=> a possibility would be to moved the footer block out of the section so that it has the .tc-content-inner as direct parent.

=> another possibility would be to wrap the_content() in a specific container to make it easier to target specifically for those kind of _content only styling_

@eri-trabiccolo opinions ? Possible without breaking too many things ?

**Comment by ghost** [comment]
fixed in https://github.com/presscustomizr/customizr/commit/b4c209cc4fdb93d47f15ff5d771bb92ca8ece050
