### ISSUE TITLE
imp:Assign filter for setting tc_grid_size ratio

### ISSUE THREAD

**Issue by JTS-IL** [Nikeo/customizr#1238]
In the world of photography there are several popular image proportions, the most common is the golden ratio, which is used for tc_grid_size.
However, sometimes a ratio of 9:16 or 3:4 or even 2:3 is better for images display.
I suggest to add a filter that allows to change the image ratio easily, without the need to add external plugin.

**Comment by ghost** [comment]
Thanks @JTS-IL for this suggestion.
@eri-trabiccolo let's discuss this point during our next meeting.

**Comment by eri-trabiccolo** [comment]
the modern style is somewhat already "ready" for this kind of change, because the grid items are "responsive", so we can pretty easily add new aspect ratios (the problem will be with some effects of gc-pro, and for the sticky one).
That was my idea, allow users to choose not the image sizes (min-height as for the classical) but among a set of predefined aspect ratios. 
So for the modern is pretty much doable. :)

**Comment by JTS-IL** [comment]
For example, my spotter's blog uses the 16:9 format, and most of the airplanes are trimmed (nose and tail).
like here:
http://www.spotting.co.il/airline/wzz/
http://www.spotting.co.il/airline/aua/
http://www.spotting.co.il/airline/bel/
and more
