### ISSUE TITLE
Why are comments not displayed on wordpress.org preview ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1253]
https://wp-themes.com/customizr/?p=1#comment-509

**Comment by eri-trabiccolo** [comment]
Most likely my fault, because in modern, by mistake, I don't display the comments section when comments are closed, and I think they are in the wp.org preview:

modern relevant part:
https://github.com/presscustomizr/customizr/blob/dev/core/front/controllers/class-controller-content.php#L265

classical relevant part:
https://github.com/presscustomizr/customizr/blob/dev/inc/_dev/parts/class-content-comments.php#L473


So that modern line should match the classical one. That should be enough

**Comment by ghost** [comment]
ah ok that's why. thanks
