### ISSUE TITLE
Any img candidate for expansion with mfp should display an expansion icon on hover

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1262]

**Comment by eri-trabiccolo** [comment]
Complicated because the 'icon' is now absolutely placed relatively to a parent image container:
- whose width/height, when not a responsive container (used in most of the lists of posts but not always), it might be too big.
- images freely placed in the content then should be wrapped in a container

We can even do the latter in php (when parsing the images to be expanded) or in js, yet the first point might drive to ugly stuff.
In js we can small this icon according to the container size, and this would be good in most of the cases, but not always.

**Comment by ghost** [comment]
Ah OK. I got the picture.
we'll find a way !
