### ISSUE TITLE
slider arrows after click => do not lose the focus and stay darker ( like if we were hovering )

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1273]

**Comment by eri-trabiccolo** [comment]
Yeah, that is how it should be IMHO, because the arrow has the focus and should be accessible with the keyboard, but it's not the case right now, because spans are not links nor buttons. 
What I think we should do is to use button tag instead of span: they will be accessible plus semantically correct.
Choose the button instead of a (link) with # href is because of accessibility.
So if you agree I will do this first. 
Then let me know what you think the arrows should appear when focused but not hovered.
