### ISSUE TITLE
WooCommerce update cart button color css

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1359]
Hi @Nikeo and @eri-trabiccolo

Customer reported this issue on helpscout.
https://secure.helpscout.net/conversation/496922658/36094?folderId=631714#thread-1350646355

I am able to replicate this issue on my test site.
Using Customizr Pro Theme Modern Style. The WooCommerce update cart button is different in color to other buttons found in cart page. It should be similar in color.

Please see screen-shot of the issue.
![screen shot 2018-01-04 at 9 36 09 am](https://user-images.githubusercontent.com/9284811/34547041-2c65eff2-f133-11e7-9e67-730585b37365.png)

Have a nice day,

Best regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Hi @denzelchia 
thanks for reporting this.

Actually that button has different color/background because it's **disabled** (by WooCommerce).
Until you change something in the cart (e.g. the quantity) that button is not clickable. (If you hover over it you'll see the "not-allowed" cursor, also the opacity is originally set by the WooCommerce style).
Once you change something in the cart (again the quantity) that button becomes available and will appear like the other buttons.
Maybe we can prevent the color changes on hover when the button is disabled, but for the rest, to me, it makes sense it has different colors.

**Comment by denzelchia** [comment]
Hi @eri-trabiccolo ,

Thank you very much for your explanation.
I will let customer know about it.

Thank you
