### ISSUE TITLE
Font awesome => upgrade to FA5

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1364]
# Why ?

- Font awesome has become some kind of web design standard, and we must provide our users with the latest version.
- It's been requested by our users several times in the past weeks. And [again yersterday](https://wordpress.org/support/topic/use-font-awesome-5-instead-of-4/) 
- There are much more icons, we went from 675 to 903
- Additional styling available, like sizing, animating, background colors, etc... https://fontawesome.com/how-to-use/web-fonts-with-css#additional-styling

# Licence ?
This upgrade raises the question of the [FA5 licensing](https://fontawesome.com/license). 

As wp.org theme author, we must use GPL compatible licenses. CC BY ... licenses don't fall in this category. 

> In the Font Awesome Free download, the CC BY 4.0 license applies to all icons packaged as .svg and .js files types.

This means that we unfortunately won't be authorized to use the fancy and fully backward compatible new svg with .js way. 
We can use 
- all icons packaged as web and desktop font files.  SIL OFL 1.1 License => GPL compatible
- the MIT license applies to all non-font and non-icon files, like css, scss, etc....

Which is enough for our need, but not the preferred way to use FA.

# How ?
The FA team has published a guide here : https://fontawesome.com/how-to-use/upgrading-from-4

But here are the specific part for us

## Upgrading the assets
The fa assets will be updated in  assets/shared/fonts/fa

![2018-01-08_10-15-24](https://user-images.githubusercontent.com/3038156/34664596-f278055a-f45c-11e7-8620-00c5c25e2696.png)

Soooo, the integration of FA5 in the Customizr theme  is pretty much documented here  
: https://fontawesome.com/get-started/web-fonts-with-css

I would like to include the sass preprocessing to build our own `fontawesome-all.css`
https://fontawesome.com/how-to-use/web-fonts-with-css#less-and-sass
Even if the build will eventually be very close to the default one.

## Upgrading the html markup

Now it looks like this 

```
<body>
  <!--user icon in two different styles-->
  <i class="fas fa-user"></i>
  <i class="far fa-user"></i>
  <!--brand icon-->
  <i class="fab fa-github-square"></i>
</body>
```

**We need to update the class name everywhere**
> The fa prefix has been deprecated in version 5. The new default is the fas solid style and the fab style for brands.

**We need to make sure we don't miss any previous icon ?**
> Version 5 changed some things. Brand icons are now their own style and references to them use the fab prefix. Also, aliases are no longer - there is one official name for an icon. Speaking of which, some icon names have changed between versions. Also, any icon ending with -o has been moved to the regular style which uses the far prefix.

Note : This upgrade will also impact all the other repos 

- pro-bundle
- all js fmk
- ...

and

- hueman
- hueman-addons
- hueman pro addons
- wfc
- fpu ?
- ...

**Comment by ghost** [comment]
@eri-trabiccolo following the discussion about far or fas, font awesome says that the new default is more fas than fab here : https://fontawesome.com/how-to-use/svg-with-js#styles-and-prefixes

> The fa prefix has been deprecated in version 5. The new default is the fas solid style and the fab style for brands.

So let's use `fas`.

**Comment by eri-trabiccolo** [comment]
UPDATE:
1) we cannot really keep the "fa" class as "fa fab" will make the 'fa' rule override the 'fab' rule (they use two different font families). We could "override" this behavior, of course...
2) some icons have been removed, at least one of our list has no substitute.
[all the social icons except for the solid and one regular (fa-envelope-o) below will be displayed as fab (brands) ]
## SOLID ICONS
Here's the list of the social icons that need the to be prefixed with "fas "
```       
array( 'fa-envelope',
        'fa-envelope-square',
        'fa-mobile',
        'fa-phone',
        'fa-phone-square',
        'fa-rss',
        'fa-rss-square',
        'fa-share-alt',
        'fa-share-alt-square'
)
```
## REMOVED ICONS WITH REPLACEMENTS (meaning that we force the replacement)
```
array(
        'fa-bitbucket-square'     => 'fa-bitbucket',
        'fa-facebook-official'    => 'fa-facebook-f',
        'fa-google-plus-circle'   => 'fa-google-plus',
        'fa-google-plus-official' => 'fa-google-plus',
        'fa-linkedin-square'      => 'fa-linkedin',
        'fa-youtube-play'         => 'fa-youtube'
)
``` 
the above replacements will happen only for the already set socials of course

## REMOVED ICONS WITH NO REPLACEMENTS
``` 'fa-meanpath'```

## OTHER VISIBLE CHANGES

- `fa-facebook` now is displayed by fa with the former `fa-facebook-square`
- `fa-google-plus` now is displayed by fa with the former `fa-google-plus-circle`
- we add the new `fa-google-plus-g` which is the former `fa-google-plus`
- `fa-linkedin` now is displayed by fa with the former `fa-linkedin-square`
- we add the new `fa-linkedin-in` which is the former `fa-linkedin`
- `fa-youtube` now is displayed by fa with the former `fa-youtube-play`

Here's a comparison between the two versions with the current (meaning the latest customizr stable version) set of icons.
With fa 4
<img width="567" alt="before" src="https://user-images.githubusercontent.com/7689242/34883105-e5e8e48a-f7b8-11e7-8c76-e22ec92c823b.png">


With fa 5 
<img width="865" alt="after_correspondency" src="https://user-images.githubusercontent.com/7689242/34883113-ee902026-f7b8-11e7-8eea-aea0cf9d96fb.png">


You can see there are repetitions, that are mostly due to the missing icons forcing process.
Users have to check their social icons display as they want otherwise they have to change them.

**Comment by ghost** [comment]
- About fa-meanpath http://fontawesome.io/icon/meanpath/, what happens after the update if a user has selected it => make sure there's no critical error in both front end and **customizer**

**Comment by eri-trabiccolo** [comment]
Set of icons for the test:
(below already with the new icons in place)
<img width="199" alt="2018-01-15_13-09-52" src="https://user-images.githubusercontent.com/7689242/34941792-8460338c-f9f5-11e7-8765-10c4ccdf1e94.png">

**Comment by eri-trabiccolo** [comment]
> About fa-meanpath http://fontawesome.io/icon/meanpath/, what happens after the update if a user has selected it => make sure there's no critical error in both front end and customizer

The icon will just be not displayed as you can see in the customizer as you can see above.
Same in front (just a "blank" space ).
Additionally, all the icons removed from the list, like google-plus-circle, will not appear in the select, producing this:
<img width="238" alt="2018-01-15_13-19-58" src="https://user-images.githubusercontent.com/7689242/34942152-d087a9a6-f9f6-11e7-978f-affd7a6ca2e4.png">

**Comment by eri-trabiccolo** [comment]
Pro bundle : https://github.com/presscustomizr/pro-bundle/pull/125
Theme customizr fmk : https://github.com/presscustomizr/themes-customizer-fmk/pull/43
Customizr front js : https://github.com/presscustomizr/customizr-front-js-parts/pull/29
Customizr : https://github.com/presscustomizr/customizr/pull/1383

**Comment by nickreiner** [comment]
Are some icons like the Patreon one intentionally left out? Can't find them through the Customizer
