### ISSUE TITLE
Mobile menu : alignment problem

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1380]
Orange should be aligned with green in the screenshot below

![alignment_issue](https://user-images.githubusercontent.com/3038156/34920506-0ff5c48e-f974-11e7-8779-3fed3a7efe07.jpg)

Reported in helpscout
> HEADER:
> 1. The horizontal menu which displays under my header logo is not in line with the logo, it wont centre evenly.
> Can you tell me how i can fix this?
> 2. where in my theme can i increase the size of the magnifying glass and shopping bag listed in the top header?
> 3. **on a mobile device when you click the drop down bar menu my menu options appear off centre to my logo, can i push them closer to the left so they're directly below the logo alignment?**
> 
> FRONT PAGE MENU:
> below my sliding vertical images is a list of menu options, there are a few issues:
> 1. How do i change the headings: SHOP, HELP, FOLLOW US, JOIN US, I need to change the size and colour of them but these headings and the options below each heading don't seem to be in the same option within font customizr?
> 
> 2. some of the links of this page are spaced different to the other headings, see how READY TO WEAR is spaced wider than the rest, do you know why this is happening and how i fix this?
> 
> FRONT PAGE:
> 1. is there a way to list the social icons in a row where i have currently listed all social links in posts under the heading FOLLOW US?
> 
> SHOP PAGE:
> 1. When you click on shop and all products are listed on the shop page, how do i remove the add to cart button, and only leave an add to cart option on each product page?
> 
> 2. How do i change the cost from green to black, and red when i list my items on sale?
> 
> JOIN US:
> on the front page i have a sign up option where customers can enter their email address and click join, the demo model showed there was an option for this but i cannot find it within Wordpress or Customizr or the CP articles?
> 
> POST PAGES:
> 1. how do i remove the number of posts comment i.e 4 posts
> 2. how do i remove the by admin, and published date all together so there is nothing written here, if it is not possible to remove how do i make it white so you cannot see anything on this page, i tried doing it but it wont change colour.
https://secure.helpscout.net/conversation/504565291/36526?folderId=607541
http://anita.theinternetprovider.net.au/

@denzelchia please comment this issue if needed with any useful customer feedback

**Comment by eri-trabiccolo** [comment]
About the menu items alignment,
ok we can do it.

About:

> HEADER:
> The horizontal menu which displays under my header logo is not in line with the logo, it wont centre evenly.
> Can you tell me how i can fix this?

Cannot reproduce this.

> where in my theme can i increase the size of the magnifying glass and shopping bag listed in the top header?

Yeah we need an option (font size). Also for the size of the menu button (width/height)
We should also split the options for mobile and desktops actually.

> on a mobile device when you click the drop down bar menu my menu options appear off centre to my logo, can i push them closer to the left so they're directly below the logo alignment?
see above: we can do it, if we want, do we? :D 

> FRONT PAGE MENU:

This is **not a theme menu** but the content of the user's front page
> below my sliding vertical images is a list of menu options, there are a few issues:
> 
> How do i change the headings: SHOP, HELP, FOLLOW US, JOIN US, I need to change the size and colour of them but these headings and the options below each heading don't seem to be in the same option within font customizr?

Since it's a custom code the only way to target them and only them in the WFC is to use a CSS class + custom control (otherwise use an h* that will be targeted by the h* in the post/page content)

> some of the links of this page are spaced different to the other headings, see how READY TO WEAR is spaced wider than the rest, do you know why this is happening and how i fix this?

cannot see this, they have all 1px (custom value set in the WFC) as letter spacing.

> FRONT PAGE:
> 
> is there a way to list the social icons in a row where i have currently listed all social links in posts under the heading FOLLOW US?

Custom code

> SHOP PAGE:
> 
> When you click on shop and all products are listed on the shop page, how do i remove the add to cart button, and only leave an add to cart option on each product page?

One should act on
a) WooCommerce template 
or
b) WooCommerce action hook
so custom code
> How do i change the cost from green to black, and red when i list my items on sale?

default WooCommerce color for the price, custom CSS is needed

> JOIN US:
> on the front page i have a sign up option where customers can enter their email address and click join, the demo model showed there was an option for this but i cannot find it within Wordpress or Customizr or the CP articles?

Cannot see the sign up option, just a link to the contact page.
Where in our demo is this option?

> POST PAGES:
> 
> how do i remove the number of posts comment i.e 4 posts
> how do i remove the by admin, and published date all together so there is nothing written here, if it is not possible to remove how do i make it white so you cannot see anything on this page, i tried doing it but it wont change colour.

All this should be possible by disabling the metas and the comments (we have options for them).
Actually we don't have a real option to not display the comments number under the post title, it only depends on the options: **Enable comments on posts** and **Display comment list**
