### ISSUE TITLE
microformats in pages > google reports missing author meta and publish/update date

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1401]
Hi @Nikeo ,

Putting up a request on behalf of customer on helpscout.
https://secure.helpscout.net/conversation/505935101/36596/?folderId=607546

Customizer requires author meta and publish/update date in a page, because his google search console reported missing author and missing update on pages.

![image001](https://user-images.githubusercontent.com/9284811/35179667-9371033c-fdd9-11e7-8bd0-66aaf9ab741c.png)

Thank you
Denzel

**Comment by ghost** [comment]
@denzelchia tnx for reporting the pb.

@eri-trabiccolo we need to check if we display the microformats for date, author, entry-title, ... the right way in pages.
see tihis old discussion : https://github.com/presscustomizr/hueman/pull/126

**Comment by eri-trabiccolo** [comment]
Mmm, date and author nope, because metas are not displayed in pages.
They've never have been, in classical neither.
Honestly not sure, have you ever seen a page with a date or the author
post-meta? (This is a real question :) )
Will investigate into this.

Il 20 gen 2018 7:58 AM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
fixed in https://github.com/presscustomizr/customizr/pull/1423
