### ISSUE TITLE
RTL in submenu items => animations should be adapted

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1414]
http://kitchance.com/

**Comment by eri-trabiccolo** [comment]
fixed in: https://github.com/eri-trabiccolo/customizr/commit/463c59c4f55c4352501b4580732b009a7ba090db
also please merge this: https://github.com/presscustomizr/customizr-front-js-parts/pull/33
for a better rtl compliance when flipping title-caret.

Don't worry, I'm on hu fa update, did this in a break :P
