### ISSUE TITLE
Adding custom fields

### ISSUE THREAD

**Issue by albertosgz** [Nikeo/customizr#1417]
Is there a way to display custom fields in posts?
I know the possibility to set custom metadata for each post, but those I don`t know how to make them displayed.
For example, I have 2 custom fields for each blog, date and place. I would like to display them.
For more info: https://torquemag.io/2016/04/use-advanced-custom-fields-depth-tutorial/

**Comment by eri-trabiccolo** [comment]
Hi Alberto,
if you're using the modern style you can override the single post part template, in your child-theme, to add your custom field code in order to display them:
https://github.com/presscustomizr/customizr/blob/dev/templates/parts/content/singular/post_content.php

Hope this helps.

Also consider that the theme support is usually provided on the wp.org support forum for the Customizr users and on [here](https://presscustomizr.com/support/) for the pro users, I close this then.
