### ISSUE TITLE
Feature request: Option to add a version number at the end of the url of each slide image

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1418]
Hi @Nikeo ,

I am putting up this request on behalf of customer on helpscout.
https://secure.helpscout.net/conversation/512949644/37054/?folderId=607544

Customer request a way to add a version number at the end of the url of each slide image.

Thank you
Denzel

**Comment by ghost** [comment]
Hi @denzelchia , thank you for reporting. this is a more code request than a feature request.
So in this case you could have replied right away that our our support won't cover code customizations requests.
Following your initial answer, you can reply that _there's no plan to add a specific option in the theme allowing users to add a parameter at the end of the url of the silde's image. Therefore this would need a custom development in php._
And since this is your second reply, you can add that code customization is not covered by [our support.](https://presscustomizr.com/terms-of-sale/)

**Comment by denzelchia** [comment]
Ok. I will make a reply to customer.

Thank you
