### ISSUE TITLE
Various blog page problems are being reported

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1424]
Reported here : https://presscustomizr.com/release-note-for-customizr-pro-v2-0-22/comment-page-1/#comment-383438
for this website http://opfietsen.nl/

> In this new release I bump into many issues with the theme. In the classical view next to the search magnify glass, I find the text fl (Like Peter finds also)
> 
> The customizer op wordpress does not work completely anymore. The preview in the screen is gone….
> 
> But on top of all of this, the static page and the blog page have real issues. I am not able to show a static page anymore, the only thing I can do is showing the blog items.
> 
> But also the seperate blog page is showing no blogs anymore. It looks like there is someting broken in the upgrade of the theme.
> 
> More people have the same issue(s)? Who can help me out?

and reported here https://presscustomizr.com/release-note-for-customizr-pro-v2-0-22/comment-page-1/#comment-383647

> Hi!
> since the updates, the blog page does not work anymore.
> When I change the theme, it does work, so I think there is something to be fixed with the Customizr update.
> May I ask you your help?
> Thanks

for this website : http://cuisinedecouverte.com

@eri-trabiccolo does it sound familiar? Did you ever come across such a bug report on helpscout or wordpress.org ?

**Comment by eri-trabiccolo** [comment]
> In this new release I bump into many issues with the theme. In the classical view next to the search magnify glass, I find the text fl (Like Peter finds also)

This is because the search in the header in the classical style is not part of the theme, but implemented with a snippet on presscustomizr.com:
https://presscustomizr.com/snippet/adding-an-html5-search-form-in-your-wordpress-menu/
which now is outdated.
see also:
https://wordpress.org/support/topic/fontawesome-is-no-more-working/

About the other two, I'm not able to replicate them here.
We might need more data.
About:
> But on top of all of this, the static page and the blog page have real issues. I am not able to show a static page anymore, the only thing I can do is showing the blog items.
> 
> But also the seperate blog page is showing no blogs anymore. It looks like there is someting broken in the upgrade of the theme.

If there's no way to show a static page on front (cannot this be done from Settings->Reading?), it means that the recent posts are shown on front, so it's normal that the "former" blog page doesn't show posts anymore => cannot have two blog pages with WordPress. Not sure is really theme related. Unless he means it happens also when setting a static front page, mmm.

The preview issue might have too many parents... :/

About the latest: http://cuisinedecouverte.com
looks like the blog doesn't contain posts (might it be because the user filters the blog with a category which doesn't have posts anymore?). The fact that it shows the 404 content after the "blog title" depends on the issue fixed here:
https://github.com/presscustomizr/customizr/pull/1405
(so not released yet).

The only big change in the latest customizr version, except for the Font Awesome, is the localization part. might that cause this kind of issue?
I see that site uses Polylang, have to test.

Will do it tomorrow as first thing.

**Comment by eri-trabiccolo** [comment]
So I tested Polylang too and nothing.
The only way I'm able to replicate this:

> Hi!
> since the updates, the blog page does not work anymore.
> When I change the theme, it does work, so I think there is something to be fixed with the Customizr update.
> May I ask you your help?
> Thanks

Is by setting an empty category in the option to filter the blog/home posts by category.
With or without Polylang.
The thing is that Polylang might make "discovering" the issue, for the user, a little more hard, as you can access the customizer in different languages, so that this case might happen:
1) French is your main language. For some reason you access the customizer in English and filter the blog with an empty category called "Test" **(this category has no correspondence in French)**
2) From now on you always access the customizer in French, since there's no correspondence in French for that category, the filter option will display you NO category. So you think you have no filter set in French, but that's not true.

**Comment by ghost** [comment]
ok thank you for this complete and detailed feeedback Rocco.
The main problem that I see for the moment is the 404 page.

I'll be focusing on building the new releases for Customizr in a moment.

**Comment by eri-trabiccolo** [comment]
Ok, so the 404 is already fixed in dev.

**Comment by ghost** [comment]
yep

**Comment by ghost** [comment]
@eri-trabiccolo is there anything we should worry about in your opinion here : https://wordpress.org/support/topic/blog-posts-page-1-not-showing/

**Comment by eri-trabiccolo** [comment]
cannot reach the user website :/ 504 gateway timeout
cannot imagine how can the theme produce the issue: Page 1 is always skipped?

Also we didn't really made any change to the wp loop code recently.

**Comment by eri-trabiccolo** [comment]
Ok now I can reach the page.
User is using another theme, and still has this problem.
<img width="959" alt="no_archive_first_page" src="https://user-images.githubusercontent.com/7689242/35640767-77b508e4-06be-11e8-9b0b-8cded6b611c8.png">


So to answer to your question:
No, we shouldn't :D

**Comment by ghost** [comment]
ok
