### ISSUE TITLE
How are we doing with the latest demo content of the theme directory => menu ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1432]
https://meta.trac.wordpress.org/ticket/30#comment:56
reminder to test it on a fresh install.

**Comment by eri-trabiccolo** [comment]
Could not spot any particular issue, except for one. All the featured pages showing the same image in the preview:
### You can see the issue here:
<img width="953" alt="new-themepreview-samefpthumbs" src="https://user-images.githubusercontent.com/7689242/36385453-e130e9ae-1592-11e8-9b99-139d2918c3ff.png">

### Here with the PR applied:
<img width="953" alt="new-themepreview-differentfpthumbs" src="https://user-images.githubusercontent.com/7689242/36777924-81d5b4fa-1c6b-11e8-847a-d96dc2bb3ce4.png">


_(Don't care about the slider, it displays nice, it's just and artifact of our screenshot taker tool)_
This is because in the latest demo content, the first post of the list has a "thumbnail" and our prevdem code doesn't handle this case.
fixed in #1469

## Additionally:
I see this in prevdem:
https://github.com/presscustomizr/customizr/blob/v4.0.18/core/class-fire-prevdem.php#L146
So I guess we wanted to remove the featured page text in prevdem. czr_fp_link, for a typo, doesn't exist when the fp is not set ()
fixed in #1469 too 
along with a fix that didn't allow the filtering of the fp link in prevdem.

Other minor thing to consider is whether or not we want to show the menu on two lines.
First of all, we don't have a great control on this (as I don't think we want to change the default menu), so what we can do, at most, is to show the main header area in full-width in prevdem.
But I think might be good to show how "nicely" a big menu aligns with this theme.
Also consider that the "dropping on two lines" can happen even if we stretch the main header area in full-width, as it depends on the preview width, so` window width` - `#customize-controls` width

**Comment by ghost** [comment]
Thanks for the PR.
I'll investigate the menu part

**Comment by eri-trabiccolo** [comment]
I updated my previous comment with the correct images.
