### ISSUE TITLE
WPForms contact form plugin compatibility

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1438]
Reported by a user :

> Also the most popular and used contact form plugin in Wordpress sites called WPForms doesn't work in some cases with your theme, with Google Chrome that is. Ex. when you have checkboxes or radiobuttons in your WPForms form. With radio buttons, it draws weird objects onto your screen/browser. With checkboxes, you can't select anything. This issue takes away many developers from your Customizr theme because there no as user friendly contact form plugins known as WPForms. Also Chrome is by far the most used browser as you might know already.

**Comment by ghost** [comment]
I'm asking the user to share an url + theme infos

**Comment by eri-trabiccolo** [comment]
I will test that too.
Might be because we hide the browser appearance (WebKit) for radios and checkboxes and use the font awesome for checkboxes, and background (or something) for radios.
What can happen is that the plug-in partially overrides our CSS leaving those in an ugly spurious stage.

WPForms, anyways, is a premium plugin.
If thinks do not change that much we can make sure our forms are compatible with:
https://it.wordpress.org/plugins/wpforms-lite/

**Comment by eri-trabiccolo** [comment]
fixed for wpforms-lite
