### ISSUE TITLE
Plugin compatibility: Jetpack and Mailchimp

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1491]
Ticket: https://secure.helpscout.net/conversation/528907349/38174/

**Comment by eri-trabiccolo** [comment]
Thanks for reporting this @emran1. 

Honestly, cannot see a direct relationship between the theme, three different plugin updates, and the products disappearing from the shop.
The "since the last Customizr update" sentence is "weird", since we're talking about something that started happening with a WooCommerce update:
latest two pro theme releases contained mostly bugfixes, so don't think they could introduce this kind of issues.

Most likely the issue there might be due to:
1) some plugin issue/misconfiguration 
2) permalinks? might be good to refresh them
