### ISSUE TITLE
Single post on mobile => huge white space below the featured thumbnail

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1524]
![schermata_2018-04-22_alle_21 21 00](https://user-images.githubusercontent.com/3038156/39291436-485dbe12-4933-11e8-9e5e-cdea779d3f87.png)

I have been able to reproduce the problem when emulating an iphone on this page
https://www.anagni5stelle.it/comunicato-stampa-06-2018-22-aprile-certificazione-lista-anagni-5s/

But not reproductible on the demo here for example : https://demo.presscustomizr.com/back-from-a-trip-in-norway/

This seems to be related to the css-centering on the user's website.
@eri-trabiccolo can you investigate on it ?

**Comment by eri-trabiccolo** [comment]
Hi @Nikeo, surely due to the js centering option not enabled.
There's a CSS fallback that should center the image (center, but not cover) in the "container", but it's buggy as far as I can see.
It should look like this:
<img width="214" alt="2018-04-26_10-03-13" src="https://user-images.githubusercontent.com/7689242/39293416-1b8b9e44-4939-11e8-987e-3f4d0ccb9567.png">
(image centered in an element with an height of 400px)
I don't know if that's ideal though...

"The problem" is that the singular thumbnail doesn't scale in mobiles (like the slider does), so that the custom height option set in the customizer is valid for all the devices.

**Comment by eri-trabiccolo** [comment]
Same happens in the classical style :/

**Comment by ghost** [comment]
can we quickly chat about it on skype ?
