### ISSUE TITLE
Fatal error: Call to undefined function WC() in core/front/models/header/parts/class-model-woocommerce_cart.php on line 30

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1529]
As reported by a user on the contact page

> I'm getting this error when i activate woocommerce on Customizr theme:
> 
> Fatal error: Call to undefined function WC() in /wp-content/themes/customizr/core/front/models/header/parts/class-model-woocommerce_cart.php on line 30
> 
> I know next to nothing about PHP, so I have no idea what can casue this problem.
> 
> I'm using Mozilla Firefox or on a Windows 10 64bit PC. But I've also had this error when using Google Chrome on Windows 7.
> 

@eri-trabiccolo are you able to reproduce it ? Does it need a fix ?

**Comment by eri-trabiccolo** [comment]
I've been not, during these months and WC had no updates in more or less one month.
Might depend on an old WooCoommerce version (weird) or maybe the user is using a beta version?
Will do some tests asap (tomorrow).

**Comment by eri-trabiccolo** [comment]
Cannot reproduce the issue with the current WC nor with the beta 3.4.0.
There might be a version where both wc_get_cart_url and WC() are not available?!
https://github.com/presscustomizr/customizr/blob/dev/core/front/models/header/parts/class-model-woocommerce_cart.php#L27

That's pretty weird though... :/

**Comment by ghost** [comment]
ok. thanks for your tests.

**Comment by ghost** [comment]
I' ve replied to the user about this.

**Comment by eri-trabiccolo** [comment]
We have a similar issue reported here:
https://secure.helpscout.net/conversation/631050884/164506?folderId=607709

This time with the classical theme.

Looking at the user plugin list, it seems the WooCommerce plugin is not installed, so all the functions that refer to WC() actually should not be called.
I cannot reproduce the issue here, and of course the majority of the users not having the WooCommerce plugin installed, do not have this issue either.

I'm not  sure under which conditions this issue might generate, it seems like this check returns true for whatever obscure reason:
https://secure.helpscout.net/conversation/631050884/164506?folderId=607709

Might be due to some obscure server related issue. But that won't be an answer for the user.
A "user side" way to fix this would be:
1) Install and activate WooCommerce
(so that the related customizer options show up)
2) Disable the WooCommerce cart in the header option.

I might propose this as a temporary workaround, specifying that this issue relates to a server side issue, and that we're about to push a new release with more pedantic checks to avoid this kind of issues happening again, if you agree @Nikeo .

Let me know.

**Comment by ghost** [comment]
I'm with you.

**Comment by eri-trabiccolo** [comment]
Well, if the whole issue has any sense (even if it's weird), WooCommerce should not be installed and activated to make the related options appear.

**Comment by eri-trabiccolo** [comment]
So since:
> Well, if the whole issue has any sense (even if it's weird), WooCommerce should not be installed and activated to make the related options appear.

I suggested the user to disable the WooCommerce header cart option in the customizer, which was visible still because of the unknown reason, and it worked fine.
