### ISSUE TITLE
Improve BuddyPress (3) support: add specific CSS when using Nouveau template pack

### ISSUE THREAD

**Issue by eri-trabiccolo** [Nikeo/customizr#1532]
https://secure.helpscout.net/conversation/584965806/162948?folderId=607709

**Comment by AiratTop** [comment]
Customizr and costomizr-pro themes have an issue with BuddyPress Nouveau template. 
Select filters are not working on Members, Activity and Groups pages.

**Example:**
![image](https://user-images.githubusercontent.com/4050715/47009310-9a8a9980-d155-11e8-96d1-a34b241e3dbb.png)

All other select filters aren't working too. 

**P.S.** I have an active license key for costomizr-pro theme (lifetime version). I wrote this issue on github, because I found this open similar issue. 

- Customizr 4.1.19
- Customizr PRO 2.1.8
- BuddyPress 3.2.0
- WordPress 4.9.8

**Comment by eri-trabiccolo** [comment]
Hi @AiratHalitov thanks for reporting this.
It seems to be a CSS conflict withe the modern theme style indeed.
I'm going to open a separate issue so we can better track it.

Thanks!

**Comment by AiratTop** [comment]
Thanks!
Looking forward to updates. :)

**Comment by ghost** [comment]
fixed in https://github.com/presscustomizr/customizr/pull/1610
