### ISSUE TITLE
Post footers author info could be improved

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1561]
> Hello to all you Customizr-devels,
> 
> I've found a possible improvement for the (little annoying) behaviour of the author-info at the bottom of a post:
> 
> /wp-content/themes/customizr/templates/parts/content/singular/authors/author_info.php
> line 17
> <p><?php echo get_the_author_meta( 'description', $author_id ) ?></p>
> 
> 
> Isn't a little ";" missing at the end? ;)
> I'd like to find here this little improvement:
> <p><?php echo nl2br(get_the_author_meta( 'description', $author_id )); ?></p>
> 
> 
> With this tweak line breaks in the author-info text will be shown in the webpages post. That would be a great improvement, I think.
> 
> Are there any reasons why (allowing linefeeds) inside the author-info text isn't implemented yet?
> (as far as I've seen only <a>-HTML-tags are being preserved)
> 
> 
> Regards & keep on doing your great job with the Customizr theme!

**Comment by eri-trabiccolo** [comment]
No required semicolon missing on that line.
Not sure what he means for all the rest (and why a semicolon there would change anything)
Will look at it asap

**Comment by eri-trabiccolo** [comment]
I don't understand if the user is saying that the semicolon will allow line-breaks in the author info.

Anyway...
Not all the HTML tags are preserved: try to save a user bio with `span`, `h*`, `p`, `br` and so on are stripped when saving - links and new lines are allowed though.
New lines do not automatically turn into `<p>`.

So what I guess is that the user is using some plugin either to enrich the author bio editor and that applies the `wpautop` on `the_author_description` filter hook, or only the second.
I guess this plugin, or a custom code, applies the filter on `the_author_description`  and not on  `get_the_author_description` (which is the one we use).

For what I can see WP by default doesn't autop `the_author_description` nor `get_the_author_description`. It actually atopd `get_the_author_description` in 4.9.0:
https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/default-filters.php#L117
But turned off in 4.9.2: 
https://core.trac.wordpress.org/browser/tags/4.9.2/src/wp-includes/default-filters.php#L117
But if the user was using WP 4.9.0 or 4.9.1, then he should not have any issue (filter applied on `get_the_author_description` hook which is called by `get_the_author_meta( 'description' )`, the function we use).

I can switch to `the_author_description`, but we might need more info in order to be sure that will "fix" the user issue.

In any case, since the author description can be autopd either by a plugin or by WP in the future (and in at least two not that old releases) we should avoid wrapping the description in a `p`, I'll use a div
