### ISSUE TITLE
issue with dropdowns with links on iPad and iPhone

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1570]
Reported on May 23rd 2018 by a user on helpscout.

> Good day,
> 
> A client of mine uses the free Customizr theme, but they're picking up an unusual error on iPad and iPhone.
> 
> The dropdown links on their site's menu does nothing when you tap on them, and these dropdowns have links on them. I'm starting at a point to try and figure this out. Has there been reports on this or are you guys aware of this issue at all?
> 
> Speak soon.

**Comment by eri-trabiccolo** [comment]
Do we know if it was on classical or modern?

Also not sure which iPhone can display a "non mobile" menu.

Anyway will try reproduce the issue and to figure it out.

**Comment by eri-trabiccolo** [comment]
Tested the modern with an iphone 7 and works fine.
The classical mobile menu doesn't have the dropdown on click so ...

Cannot test ipad except with chrome emulator.

If it's about the modern theme, then we should know which are the user's devices experiencing this issue because it might depend on the "flex framework" which doesn't support old browsers/systems.
