### ISSUE TITLE
Simple option to display an absolute positionned header

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1597]
The goal is to easily go from this : 
![2018-10-03_00-09-55](https://user-images.githubusercontent.com/3038156/46379913-ae87c300-c6a0-11e8-84d2-dedd87066043.jpg)

to this : 
![2018-10-03_00-04-54](https://user-images.githubusercontent.com/3038156/46379810-56e95780-c6a0-11e8-9b3b-34284a8be58b.jpg)

### styled applied for the example
```
[data-czr-model_id="header"] {
    position: absolute;
    width: 100%;
    background: transparent;
}
```

### the style of the mobile menu expanded is broken
![2018-10-03_00-11-35](https://user-images.githubusercontent.com/3038156/46380027-150ce100-c6a1-11e8-8f19-d440a22f0686.jpg)

### the style of the search expanded on mobile is broken
![2018-10-03_00-13-48](https://user-images.githubusercontent.com/3038156/46380080-4685ac80-c6a1-11e8-8891-1ab16f650e3f.jpg)

**Comment by ghost** [comment]
- for home only
- option located in header design, below the header style

**Comment by eri-trabiccolo** [comment]
So I did the first prototype for this as agreed, removing the box-shadows but keeping the light borders, you can find it at this branch of mine:
https://github.com/eri-trabiccolo/customizr/tree/transparent-header-prototype

We will just apply an alpha factor of 0.9 (Hueman alike, even if in that case is .85) to the backgrounds of dropdown elements, mobile search box and mobile collapsible menu.

The "background transparency rules" apply to the header elements only when the header is not sticky+page scrolled, because in that case the "semi-transparency" is controlled by another option:
https://github.com/presscustomizr/customizr/blob/v4.1.13/core/core-settings-map.php#L625

The "background transparency rules" will not apply to the side menu, even if it follows the header skin rules (see the screenshot below with a pro opening effect):
<img width="371" alt="2018-10-04_15-50-48" src="https://user-images.githubusercontent.com/7689242/46479880-58299a00-c7f0-11e8-958b-503e18960a7c.png">
(in the future we might consider having a separated skin selector for the sidenav too.)

### Considerations:
1. I think we need to split this option for mobile and desktop. Think about having the contact info in mobiles that make the header grow, while the slider gets smaller, you might easily end up having the header "overflowing" the slider or so.
2. The contextualization it's really needed when using this option even if only for the home page. That's because if you enable this option for the home page, in most of the cases you will be forced to use a pretty dark header style (=> light foreground). which will propagate sitewide, and this might be not really what you want.
3. Might be good to add an option to apply a light/dark filter to the slider, at the moment we only allow having a filter or not. Would be even better if this could be done per slide and not only per slider.

**Comment by ghost** [comment]
OK Thanks. I'm finishing things on Nimble and look at your dev.
