### ISSUE TITLE
Event Calendar : issue when activating the block editor for events

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1643]
> Hello,
> after updating our development environment merkmaltext.de to WP 5.0 there seem to be a conflict with "The Events Calendar" using Gutenberg block editor:
> 
> I have enabled "Activate Block Editor for Events" in the settings->General->Settings (TEC). If I want to use the block-icon-date-time provided by TEC, I cannot make any changes.
> However, this is possible with the standard theme twenty nineteen.
> 
> Best Regards,

https://secure.helpscout.net/conversation/729938066/166544?folderId=607544

**Comment by ghost** [comment]
@eri-trabiccolo i've assigned the conversation to you on helpscout
Let me know if you need to discuss it on skype

**Comment by eri-trabiccolo** [comment]
Hi @Nikeo 
I'm unable to really "reproduce" the issue, because here with that option enabled, WP 5.0.1 + 2019 theme, creating a new event results in a blank page with the following js error:
![schermata 2018-12-13 alle 11 02 10](https://user-images.githubusercontent.com/7689242/49931249-c2347e80-fec6-11e8-8431-301ce29e63fa.png)

Same thing with WP 5.0.1 + Customizr.
(the client uses TEC-Pro, which maybe behaves differently)
Cannot really test then.

Can you?

**Comment by ghost** [comment]
user will keep us informed
closed for now
