### ISSUE TITLE
is the Simple Image Size plugin a good solution that we can recommend ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1670]
to allow users modifying the default img sizes without diving in the code ?
https://wordpress.org/plugins/simple-image-sizes/

The plugin allows user to modify the image sizes of the theme and regenerate the thumbnail.

I've taken a quick look and it seems to work fine for the image sizes that I have tested : slider size and tc-grid-size

The question is : are we sure that, given our current code, any img size can be modified in Customizr and Hueman ?
Can you let me know your opinion about this @eri-trabiccolo when you can.

**Comment by eri-trabiccolo** [comment]
I remember I used that plugin and also suggested it to one of our users... (probably to remove some image sizes too).

Except from our code, which I think is fine, the problem is that at least for Customizr, changing the thumbnail sizes means something near to 0 in they way they will look :)
Except for the Masonry and the "Plain" grids all the other elements using them assume certain sizes.
The "wrapper" sizes (CSS) are based on the original image sizes, they don't dynamically adjust over the actual image sizes. 

So, yeah, we can suggest that plugin, but I don't think it will solve the real issue the user wants to solve.

Not sure I've been understandable... :)

**Comment by ghost** [comment]
Yes you are understandable :) The image, whatever their sizes, will fill their wrapper.
But at least, recommending a plugin will avoid requests from user wrongly using this type of snippets : https://presscustomizr.com/snippet/changing-default-image-sizes-customizr/ !

**Comment by eri-trabiccolo** [comment]
Yeah totally! :)

**Comment by ghost** [comment]
ok. Link added in the snippet and in the doc.
