### ISSUE TITLE
audio post format : display the featured image above the audio player

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1671]
When there's a featured image.
Requested here : https://secure.helpscout.net/conversation/761724335/167413?folderId=607547

@eri-trabiccolo was there a specific reason why we decided not to display the feat. image when designin this audio post format ?

**Comment by eri-trabiccolo** [comment]
The audio post format was designed to display the player only yes.
Consider that depending on the "service", and on the post list design, the audio player could be pretty big.

That was a designer's design choice we approved (see the prototype website) :) 

I think we display the audio post format image in the classic grid post list layout though...

**Comment by ghost** [comment]
OK thanks.
Let's display this featured image in the modern then.
It would be great if you could work on it. Can I add this to your column ? No rush.

**Comment by eri-trabiccolo** [comment]
For which list of posts?
In the alternate layout the featured image "place" is totally taken by the player... e.g. when using a spotify audio, as you can see on our prototype_website/grid-alternate-full.html

Having both will be terrible.

**Comment by ghost** [comment]
oh yes.
Let's say in every grids but alternate ?

**Comment by eri-trabiccolo** [comment]
Mmm ok, let's see :D

**Comment by eri-trabiccolo** [comment]
(needs to be planned)

**Comment by ghost** [comment]
I add it to your column in the customizr group

**Comment by eri-trabiccolo** [comment]
After some investigation, I ended up to make this addition only to the masonry grid layout (pro). Because:
1) as we said this shouldn't be applied to the Alternate layout
2) the "classical" grid just doesn't show any post format additional media, the featured image is always shown instead
3) the "plain full" layout, always shows the featured image, and then the audio/video/quote/link just before the content
4) the "plain excerpt" layout, always shows the featured image, but never the audio/video/quote/link before the excerpt

see https://github.com/presscustomizr/pro-bundle/pull/155

**Comment by ghost** [comment]
ok. perfect.
So the featured images was already displayed in all grids but masonry.

**Comment by eri-trabiccolo** [comment]
And alternate, where it's still not displayed.

**Comment by ghost** [comment]
yes
