### ISSUE TITLE
Front page slider character limitation is not working in Japanese

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1675]
https://secure.helpscout.net/conversation/766726759/167553?folderId=607547
> Hi,
> In multi-byte character environments such as Japanese, the limit of the number of characters of the front page slider (80 characters) does not work with theme option.
> All excerpts are output, so the "read more" button overflows on mobile devices.

**Comment by eri-trabiccolo** [comment]
Yeah this is an actually "old" thing.
It has to do with the PHP multibyte support.
Consider that even the standard WP excerpt should have the same problem.

see https://github.com/presscustomizr/customizr/pull/557

**Comment by ghost** [comment]
is there anything we can do ?

**Comment by eri-trabiccolo** [comment]
When I "studied" the problem I've found the "multibyte compatibility" was the issue.
I think that's still the problem.

If I'm not wrong there was a WP plugin that performed the mb compatibility for the WP functions.

We use a custom function to trim the text, which is not multibyte compatible, and we can make it mb compatible (if the PHP module is enabled, otherwise I think we cannot do anything).

**Comment by ghost** [comment]
ok.
I'll add this issue to the "known problem list" then.
And reply to the user that there's unfortunately no solutions.

**Comment by eri-trabiccolo** [comment]
Ahaha,
well but there is: implement the mb compatibility for our own text trim function.
Which is something I did in the PR I linked before.
The only thing, then, is to port it to the current text trim function code, and test, and stuff.

**Comment by ghost** [comment]
ah ok, sorry I'm tired :)
OK so I put it in your column then
