### ISSUE TITLE
Why the search form is broken when inserted in a Nimble section with the Customizr theme ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1682]
see here : https://demo.presscustomizr.com/this_is_a_404_error_page
@eri-trabiccolo I think you'll know how to fix this. I put it in your column.

Ideally the fix should be a PR in the customizr theme. But let me know if some adaptations are needed on Nimble side too.

In a near future, Nimble will have its own search module, for which the style will be theme agnostic. see https://github.com/presscustomizr/nimble-builder/issues/342

Thanks

**Comment by eri-trabiccolo** [comment]
Yeah, will check asap, not sure why, it's (or at least should be) a js issue.

**Comment by ghost** [comment]
ok.
It works on this user's page : http://www.chimpampum.com/es/sdf%20sldfkj

**Comment by eri-trabiccolo** [comment]
So, the thing is that in the demo you use a nimble template, and in this case you don't load the Customizr front JS assets see:
https://github.com/presscustomizr/customizr/commit/0009966894bb3ecc36aa1846474f52c7ab8cd542

So, if you want, what I can do is "trying" to reverse the Customizr search form logic, meaning that by default it'll be "expanded", and will be collapsed via js.

I would say, that, alternatively, we could add custom CSS code to the Customizr theme as we know the nimble templates are all wrapped in `#nimble-page` element.

But... well, the thing is that in https://github.com/presscustomizr/customizr/blob/0009966894bb3ecc36aa1846474f52c7ab8cd542/core/class-fire-resources_styles.php#L54
you clearly wanted to avoid the loading of the CSS assets as well, but this is currently not working as expected, otherwise we wouldn't even have this issue in the first place :D 
In any case when  `czr_fn_is_full_nimble_tmpl()`we can disable this filter, so that the Customizr modern theme doesn't override the search form html:
https://github.com/presscustomizr/customizr/blob/dev/core/class-fire-init.php#L260

Let me know what you think about this then :D

**Comment by ghost** [comment]
Ok thanks for the analysis.

alternative way : since the search form will be turned into a module for Nimble soon, and that the Customizr modern search form style + animation is good => we could port Customizr search form style + js ( + markup in the future module ) in Nimble.

So, I'll open an issue for Nimble to 
- identify the search form style + js that we need to port from Customizr modern to Nimble
- add those assets to the Nimble _scss + front js files.

**Comment by ghost** [comment]
I'm closing this issue. There's nothing to change in the Customizr theme then.
