### ISSUE TITLE
compat issue with plugin ultimate-social-media-icons

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1683]
https://de.wordpress.org/plugins/ultimate-social-media-icons/

> I wanted to use the plugin
> https://de.wordpress.org/plugins/ultimate-social-media-icons/
> 
> When I activate it, I get the following error:
> 
>     Error : Please fix your theme to make plugins work correctly: Go to the Theme Editor and insert <?php wp_head(); ?> just before the </head> line of your theme’s header.php file.
> 
> I’m not the only one with this problem:
> https://wordpress.org/support/topic/error-please-fix-your-theme-to-make-plugins-work-correctly/
> 
> Can you help?
> 
> Can you fix this or do you recommend an other plugin for social sharing? Or do I have to fix it?

**Comment by eri-trabiccolo** [comment]
Won't fix.
What's the actual issue there?
Of course that "error" is not an error, it's just that the plugin assumes you have to have the wp_head() call in the header.php template file, and this theme doesn't and never did, but of course we have the wp_head() call in the <head> tag. That's what matters, not what a plugin thinks.

**Comment by ghost** [comment]
sure. of course we know it's not an error. The idea is to try to be compatible with this plugin used by 200k+ users.

**Comment by eri-trabiccolo** [comment]
The classical style calls the wp_head() using a hook.

The modern style has a head-no-model template, which is required here:
https://github.com/presscustomizr/customizr/blob/dev/templates/header-no-model.php
which as you know is required with an action hook here:
https://github.com/presscustomizr/customizr/blob/dev/header.php#L16

So, since the plugin "check" is stupid, what we can do is to move the whole classical 
`CZR_header_main::$instance->czr_fn_head_display()`
here:
https://github.com/presscustomizr/customizr/blob/dev/header.php#L32

so that the `wp_head()` call would be in the header.php template. And everybody will be happy, except the users who used to use hooks for I don't know what purpose :D 

I'm going to be on it :)

**Comment by eri-trabiccolo** [comment]
Do you know that the plugin has a special case for Customizr, and Customizr only? :D 
`            if(isset($currentTheme) && !empty($currentTheme) && $currentTheme->get( 'Name' ) != "Customizr"){
`

**Comment by ghost** [comment]
yeah sounds like perfect work around

**Comment by ghost** [comment]
oh that's funny. But what does this special case do then ?

**Comment by eri-trabiccolo** [comment]
It doesn't print the notice (but still runs the check :S) when using the Customizr theme.
The same doesn't apply when the theme is Customizr-Pro or even a child-theme of Customizr, as 
`$currentTheme = wp_get_theme();`
and not, when needed, the parent theme. :)
