### ISSUE TITLE
Featured Image in singular => WooCommerce product singular should not inherit by default the single post setting

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1708]
https://wordpress.org/support/topic/bug-full-width-cover-show-with-woocommerce/#post-11324627

### SPEC
- add a checkbox option in WooCommerce customizer section > below thumbnail width
- control text : same as for the post
- unchecked by default, for users start using Customizr after next version
- the registration is done with the usual filter, and added to the compatibility code
- image size => use our size and fallback on the original

**Comment by eri-trabiccolo** [comment]
from #1704 

> This might be not ideal.
> Do we want to add a specific option to prevent WC products from being impacted?
> 
> Note:
> this is true only if we show the single post featured image BEFORE the title in full-width, as we print it using an hook available in single products too, while the hooks used to print the featured image in different locations are not.
> 
> reported here:
> https://wordpress.org/support/topic/bug-full-width-cover-show-with-woocommerce/

**Comment by eri-trabiccolo** [comment]
About the specs:
**add a checkbox option in WooCommerce customizer section > below thumbnail width**
no way to insert an option between two WooCommerce options because they use no priority param.
It'll look like this:
![Schermata 2019-03-19 alle 16 42 17](https://user-images.githubusercontent.com/7689242/54620584-af51bd00-4a66-11e9-8a90-583e607b32d3.png)


**control text : same as for the post**
the post text is not relevant so I used a different one

**the registration is done with the usual filter, and added to the compatibility code**
Since we add the option to a specific WooCommerce section, we don't really need the "usual filter" (on the active_callback), but I kept it anyways.


@Nikeo, we're missing a couple of options here:
1) Thumbnail's max-height 
2) Thumbnail's max-height in mobiles:
![Schermata 2019-03-19 alle 16 53 01](https://user-images.githubusercontent.com/7689242/54621107-81b94380-4a67-11e9-89e4-7b8927fce5d0.png)


I think we should add those for the product, it's only about some CSS dynamically added, there's no image size involved, so I'll add them.

**Comment by ghost** [comment]
ok.
about the max height for desktop and smartphone. I would prefer that you don't add those 2 additional options.
=> The idea of this new option is to disable the featured image on products. Adding height customization options doesn't send the right signal.

**Comment by eri-trabiccolo** [comment]
What would be the height then? The single post thumb height I guess (I mean, that's how it works now).
So we add a notice that will point to the single post thumb height controls.
Fine for me.

**Comment by eri-trabiccolo** [comment]
So according to this:
https://secure.helpscout.net/conversation/807132699/216669?folderId=607544

we shouldn't enable the new option by default for older users, but make it depend on the single post featured image option value, right?!

@Nikeo ^

**Comment by ghost** [comment]
yes we wrongly assumed that all users had enabled the post featured image on top of their single post.

Let's make it simple now and simply disable it by default. users who need to display it will have to manually activate it.
I'm on it.

**Comment by eri-trabiccolo** [comment]
Yeah definitely better disabling it by default.

**Comment by eri-trabiccolo** [comment]
reported here too I guess:
https://wordpress.org/support/topic/double-featured-image-in-woocommerce/

(you "cited" me with the wrong nickname who's this 4z_c0nf? :P)
