### ISSUE TITLE
Gutenberg editor compatibility improvements whith cs

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1728]
following https://github.com/presscustomizr/customizr/issues/1705

@eri-trabiccolo let's decide which compat will be ported to Customizr cs among those : https://github.com/presscustomizr/customizr/issues?utf8=%E2%9C%93&q=gutenberg

First candidates : 
- editor style => the idea would be to adapt the PR https://github.com/presscustomizr/customizr/commit/01124dc98e5c4d8294ab4620803e71e8580b6de4 to the cs
- embed block => reported here https://secure.helpscout.net/conversation/825190671/216925?folderId=607541

**Comment by eri-trabiccolo** [comment]
the only "problem" is that I still cannot find a way to know, at the stage we enqueue the styles, whether or not we're in the block or the classic editor, hence, for the classical style both styles coexist, with the style of the classic editor that can impact on the block editor too (as it was before).

**Comment by ghost** [comment]
OK thanks . this is crazy that there's not a simple boolean core function letting us know whether or not the new editor is loaded. I can't believe they did not think about this

**Comment by eri-trabiccolo** [comment]
It's embarrassing, maybe I'm too dumb to find it, cannot find anything on internet, I can find a handy method in the Classic Editor plugin, but... guess what? It's a private method!

**Comment by ghost** [comment]
maybe a solution here ? 
https://wordpress.stackexchange.com/questions/320653/how-to-detect-the-usage-of-gutenberg

**Comment by eri-trabiccolo** [comment]
Well, not really, as you can read there none of those methods can tell you if you're currently in the classic editor.

Look that the following is totally fine if you need to enqueue assets ONLY for the block editor:
`add_action( 'enqueue_block_editor_assets', 'your_function_name' );`
but I mostly need the opposite, enqueue something only if is classic editor, and this doesn't seem to be possible, once you declare the support for the `editor-styles`, because in that case, the function `add_editor_style` will work both for the classic and the block editor style.

Maybe we have to remove the support for the editor-styles, handle all the block editor styles with the action hook above, and all the classic editor style with `add_editor_style` as it was before.

But do not declaring such a support for "modern" themes might have some other side effects.
Have to test..

**Comment by eri-trabiccolo** [comment]
The user in https://secure.helpscout.net/conversation/825190671/216925?folderId=607541

confirmed the "embed" issue was due to a plugin conflicting with the Gutenberg responsive embeds (which this theme, either in classical and modern styles, supports)

**Comment by eri-trabiccolo** [comment]
about the block editor detection problem:
https://make.wordpress.org/core/2019/04/17/block-editor-detection-improvements-in-5-2/

**Comment by ghost** [comment]
yep I saw it too. This is welcome !
