### ISSUE TITLE
mobile menu => javascript tap / click event possible issue

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1733]
> Mobile menu stops working with Draw Attention plugin

> Here is the fix for another theme that was having similar issues. Basically, the JavaScript is listening for both a tap and click - unless the default is prevented, both actions fire on touch screens. https://wordpress.org/support/topic/mobile-menu-issues-on-pages-with-draw-attention/
> 
> Wordpress 5.1.1-en. CustomizrVersion: 4.1.37. Draw Attention Version 1.8.9 | By N Squared. Here is the site I am referencing, and the Draw Attention plugin is being used on the "Get Involved" menu page. http://pranichealingrichmond.com/

https://secure.helpscout.net/conversation/825871704/216938?folderId=610151

**Comment by eri-trabiccolo** [comment]
@Nikeo I went on the user's website on the "Get Involved" page and I cannot see any JS issue with the mobile menu. The issue there is that this "Draw Attention" content overlaps the mobile menu, because of a z-index "conflict". That's all.
You might want to instruct the user to increase the header z-index, we have an option for that.

**Comment by ghost** [comment]
OK Thanks. Are you positive (test ) that increasing the z-index fixes the problem ?

**Comment by eri-trabiccolo** [comment]
Only on the user website, didn't test it locally :D
a z-index of 401 seems to be fine
