### ISSUE TITLE
Too much space when using Customizr with Elementor Text Editor

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1759]
Hello, 

I am writing this because I encountered a problem which I believe is  related to Customizr (using the latest: 4.1.41). The theme is perfect  for the current website we are building right now but this issue is  really holding us back, perhaps even from purchasing a pro version. 

> It has to do with Elementor's Text Editor and extra space above and below the text. Picture 1 (https://imgur.com/a/aeGnrJt)  shows how it should be and Picture 2 how it currently is. 

![D9otFrM](https://user-images.githubusercontent.com/3038156/59365571-0949e200-8d39-11e9-8536-52063c4fc985.png)
![F79wg4H](https://user-images.githubusercontent.com/3038156/59365578-0e0e9600-8d39-11e9-9efc-db85750fd3b4.png)
> 
> Every new  Text Editor that I drag & drop into the workspace, the same thing  happens. I am also providing a website photo to give you an idea how it  looks on the website. 
> 
> I am operating on the newest version of Wordpress and newest plugins,  everything is up to date. 
> 
> I already tried changing Line Height in  Elementor, deactivating all the plugins, installing a fresh copy of  Firefox (which I don't even use) and opening a website there but to no  avail. 
> But when I switched a theme to a default Twenty Sixteen, the  space actually vanished so I have reason to believe this is related to  Customizr. I am using Chrome as a default browser and Windows 10. Any  ideas what to do next are much appreciated. 
> 

![5YmXe7R](https://user-images.githubusercontent.com/3038156/59365567-06e78800-8d39-11e9-8602-c5bcf3327f01.png)

**Comment by eri-trabiccolo** [comment]
By design the theme `<p>` margins are : 
```
margin-top: 1.25em;
margin-bottom: 1rem;
```

and h* margins are:
```
margin-top: 1.25em;
margin-bottom: 0.5rem
```

Do we want to force them to 0 for elementor widgets? The user then can use elementor's options to add margins/paddings.

The only problem is that if we're going to do so we will impact on all our users using elementor that don't find this annoying at all, or even a good choice since it aligns by default the style of the posts created without elementor with those created with elementor.

**Comment by eri-trabiccolo** [comment]
I've looked again into this.
I don't think we have to do nothing.

To "remove" those spaces, we should add a rule like:
`.elementor-text-editor p { margin: 0}`

This means that two **p** one on top of each other will have no space between them, which is totally inconsistent with the behavior of **p**s throughout the site. Also the user has no control on these **p** spacings because Elementor has no "p" element, it has the text editor, where you can have p and h etc etc.
You can only change the line-height of these **p** through Elementor's settings, which is not the same thing.

Are we sure we want this?
I'm not confident applying this just for one and one only request...

**Comment by ghost** [comment]
I agree. 

When you say : "_I don't think we have to do nothing._" => you're suggestion is to keep it as it for the moment, right ?

**Comment by eri-trabiccolo** [comment]
Right,
I don't think we have to introduce such a change at the moment. If and when the amount of this kind of request will be significative we'll do it, if you agree.

**Comment by ghost** [comment]
yep, totally
