### ISSUE TITLE
Display navigation in pages => when active, should not be displayed on home

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1764]
I just discovered that when home is a front page, the page navigation is displayed when enabled.

![2019-07-01_15-28-15](https://user-images.githubusercontent.com/3038156/60440389-03973c00-9c15-11e9-9ea9-72adaaf1b965.jpg)

**Comment by eri-trabiccolo** [comment]
I think that this will require a new option to be added (for old users wanting the navigation there...), display post navigation in home...
which will target both static front page and home blog.

**Comment by eri-trabiccolo** [comment]
Looks like we already have an option that targets ONLY the home when displaying the latest posts, and only shows in the frontpage sec:
![Schermata 2019-10-23 alle 10 18 05](https://user-images.githubusercontent.com/7689242/67372600-6f176780-f57e-11e9-9b48-40273c7d2c1d.png)

that option only shows up when Front page displays option is set to "Your latest posts".
If you agree @Nikeo I would change that option label and make it apply to both static and blog front pages.

**Comment by eri-trabiccolo** [comment]
fixed in #1786 

**NOTE:** The options that controls the pagination displaying in static front page NOW is the same that controlled the pagination displaying in home displaying the latest posts, which is TRUE by default. This means that old users could see the navigation appearing on their static front page.

They have to be instructed on where to disable it.

I know this could be not ideal but the alternative would have been creating an additional option for that context only. We already have tons of options. Let's doc it and stop.

**Comment by ghost** [comment]
OK got it thanks!
