### ISSUE TITLE
Feature request: User wants modern style sticky header exactly like the classic theme.

### ISSUE THREAD

**Issue by emran1** [Nikeo/customizr#1775]
There's a bit different in both's function as mentioned in the ticket that on modern theme the sticky menu only appears when you scroll down and then scroll up a bit again

https://secure.helpscout.net/conversation/933461487/218338?folderId=1845241

**Comment by eri-trabiccolo** [comment]
Hi @emran1 
thanks for opening this.
Actually, in modern style, the sticky menu appears:
- when you scroll down and then scroll up a bit if the **Destkop/Modile: header menu visibility on scroll** is set to **Reveal on scroll up**
- when you scroll down after a certain "offset" if the **Destkop/Modile: header menu visibility on scroll** is set to **Reveal on scroll up** is set to **Always visible**

I agree that "Always visible" is misleading, and yes it doesn't behave as in the classical style but that's by design also to remedy to some intrinsic problems the solution adopted in the classical style can show.
