### ISSUE TITLE
[Event Calendar] Customizr Pro conflicting with The Events Calendar category view

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1782]
reported here : https://secure.helpscout.net/conversation/976349670/218859?folderId=607547

> Hi,
> 
> I'm using the Customizr Pro theme for a redesign on a website I'm currently working on. This website also uses the The Events Calendar by Modern Tribe, a plugin which should be fully compatible to the theme according to the articles on your website.
> 
> However, when I'm using the "Adding Event Categories to Navigation Menus" feature of the calendar plugin, the Customizr theme seems to override the calendar's post list style and replaces it with its own. See the attached screenshots for what the category view looks like now and what it should look like.
> 
> Since I don't have this issue with other themes, this seems to be a problem with the Customizr theme. Is there a way to fix this?
> 
> Best,
> Daniel

**Comment by ghost** [comment]
@eri-trabiccolo is it possible for you to explore this one ?

**Comment by eri-trabiccolo** [comment]
Sure, hardly today though.

**Comment by ghost** [comment]
great thanks. sure, of course.

**Comment by eri-trabiccolo** [comment]
@Nikeo 
I don't seem to be able to reproduce it, works fine here. 
![Schermata 2019-10-10 alle 09 48 08](https://user-images.githubusercontent.com/7689242/66549294-46857b80-eb43-11e9-9b0f-7eca7e1c4cc5.png)

Might be due to a conflicting plugin, that impacts on the Customizr theme but not on other themes?!

**Comment by ghost** [comment]
The problem can be reproduced on (private site) https://www.fzs.de/wordpress/themedev/?tribe_events_cat=seminare

We'll discuss it during the next dev chat

### With Twenty Nineteen
![2019-10-23_15-25-23](https://user-images.githubusercontent.com/3038156/67397497-89b30600-f5a9-11e9-99da-eb9630ee71d8.png)


### With Customizr
![2019-10-23_15-25-40](https://user-images.githubusercontent.com/3038156/67397506-8d468d00-f5a9-11e9-95a6-0dad427d7d30.png)

**Comment by eri-trabiccolo** [comment]
quoting myself :D 

> Might be due to a conflicting plugin, that impacts on the Customizr theme but not on other themes?!

Meaning that we need more info...

**Comment by ghost** [comment]
I've tested the problem on the user's website, with no other plugins enabled.
I don't know where it comes from exactly.

**Comment by eri-trabiccolo** [comment]
Ah, cool, that's an additional info :D

**Comment by ghost** [comment]
yeah. this is such an impressive problem solving process is it ? :)
anyway, not a priority for now.
thanks

**Comment by eri-trabiccolo** [comment]
Anyway I'm able to reproduce the issue locally when changing the permalink from a "sane" (aka pretty permalink) structure like the Post Name one to the Plain one (http://one.wordpress.test/?p=123)

For some reason the user website uses the Plain structure.

We rely on some events calendar code to understand whether or not instructing our theme to load a singular template instead of an archive one (you know we have our rules and hooks for that).
Probably if the site doesn't use pretty permalinks this events calendar code we rely on doesn't work as expected...

We can investigate furthermore but we can even say use pretty permalinks, there's no reason in the word to not use them, except some server configuration preventing them.

**Comment by ghost** [comment]
OK Thanks
