### ISSUE TITLE
[Post slider] explore a way to remove repeated posts, which are already displayed in the slider.

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1817]
This is a topic already discussed in the past.
Requested here : https://wordpress.org/support/topic/remove-repeated-posts/
@eri-trabiccolo can we discuss on how to approach the problem ?

**Comment by eri-trabiccolo** [comment]
@Nikeo 
yes sure.
Although this means that we have to "fire the slider" around `pre_get_posts` so that we can alter the main query.
- the idea would then be:
slider instantiated at pre_get_posts | 0 -> if slider of posts, save the posts in an "global" variable (actually a `CZR()` property`
- at pre_get_posts | ? -> check that property and exclude those posts (and filter the stickies as well... )
