### ISSUE TITLE
[Large screens] narrow container => let's keep thinks as they are

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1845]
https://secure.helpscout.net/conversation/1156312158/221173/

Hello @eri-trabiccolo , your contribution would be welcome on this. Could you also explore this problem when you'll have the time ?
Thank you

**Comment by eri-trabiccolo** [comment]
I don't see the problem @Nikeo 
unless we want to add a new option to have a full width "template".
Am I missing something?
(sorry haven't seen this, I replied on hs).

**Comment by ghost** [comment]
You're not missing anything. Sorry I should have provided more details.

The problem pointed by the user is that on a large HD device, the container max-width, as defined in the Customizr theme, limits the width to a maximum of 1140px.
Here : https://github.com/presscustomizr/customizr/blob/dev/assets/front/css/_dev/custom-bs/custom-bootstrap.css#L350


And the result is a content looking narrow in the middle of the screen 
![2020-06-05_16-28-17](https://user-images.githubusercontent.com/3038156/83889284-4168e280-a74b-11ea-86bb-8d5d9a21d24b.png)

In fact it's not really a retina problem, but more a device's width one. I think that the problem to solve here is how to maybe adapt the container max-width to very large screens.

So I was wondering about the possibility of defining a new media query for large HD screens that would set a larger container max-width.
According to this study, https://www.hobo-web.co.uk/best-screen-size/, 3% of user screens are wider than 1440px. Which is the case of our user.

A possibility would be to define a new media query in which width would become dynamic, like this for example : 
```CSS
@media (min-width:1440px) {
 .container {
  max-width:80vw;
 }
}
```

But this raises the question of possible unwanted side effects.
What do you think ? Is it the right problem to solve for you ?

**Comment by eri-trabiccolo** [comment]
Yeah I see what you mean, and I'm not sure it's a problem, maybe it is but I'm not sure :) 
Some of our thumbnail sizes are based on the container's width, e.g. the galleries highly rely on that, masonry image sizes too.
Also, our slider boxed image size is based on that.

Also, github.com has the same problem, and I guess a lot of other sites :D 
I'm not sure, maybe he's right, I have a pretty big screen (27") and I never navigate in fullscreen, doesn't make any sense to me. The text will take the full width but most of the images do not, because I hope you don't fill you're article with images 2000px width :D 

We can probably do that without soooooo many side effects, but I really wouldn't know how to handle our galleries without having them look pretty ugly on very large screens. 

Let's look at the demo about page with your rule above:
![Schermata 2020-06-05 alle 17 27 51](https://user-images.githubusercontent.com/7689242/83894728-fb634d00-a751-11ea-8246-703230b22fc6.png)

Is it good?
I think that's just not the resolution to look at a website :D 

There are implications then, and this means that, to me, we need at least to make it optional.

IMHO

**Comment by ghost** [comment]
OK thanks for this analysis. Yes this convinces me. I tend to be in line with your position which is to keep our current max-width for the container, as most website do.
