### ISSUE TITLE
[Menu] right clicking a parent menu item breaks sub-menu items auto-collapse

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1852]
https://wordpress.org/support/topic/issue-if-the-menu-is-right-clicked/

**Comment by PeopleInside** [comment]
*following*

**Comment by PeopleInside** [comment]
Hi, the issue is present also without the right click just keep the click pressed on the menu voice then drag a little the voice out of the menu and release. 

Hope you will fix this. Thanks.

![pi custmz issue](https://user-images.githubusercontent.com/5006150/93721397-42a20c00-fb90-11ea-9f6a-2ff807998135.gif)

**Comment by PeopleInside** [comment]
Hi @Nikeo hope you are well!
I know you are busy but if you get a beautiful day with some free time and inspiration I will be happy if you could help me to fix this menu issue that force the visitor to refresh the page for resolve the bad visual issue.

I'm asking help on various websites (because know maybe you are busy and cannot look soon at this) but i don't get any help.

I'm trying to searching a solution on the web.
I found this https://stackoverflow.com/questions/21203111/bootstrap-3-collapsed-menu-doesnt-close-on-click maybe so can be something related to bootstrap? I don't know if this can be usefully. I'm not good in programming and fixing theme issues.

Seems if is a jQuery or script I need update from you as will be not easy for me to fix.

Have a good day and thank you for opening an issue here considerate the issue. I appreciate that.

**Comment by PeopleInside** [comment]
Oh.. thank you !!! Will try now.

**Comment by PeopleInside** [comment]
Umh seems I cannot fix directly on my stable theme.
I need wait an update from your part. Thanks for fixing, I cannot test but will sure will be resolved.
