### ISSUE TITLE
Minimize # of db queries

### ISSUE THREAD

**Issue by fe-data** [Nikeo/customizr#1872]
I really love this theme and I'm using it on several sites.

Nevertheless I think there is some room for improvement. Debugging it with 'Query Monitor' shows a lot of duplicate db queries. Wouldn't be better to cache the options in a private variable  in the function 'czr_fn_get_raw_option' once they are read. Its only a few lines of codes to accomplish that.
![Screenshot 2020-12-02 17-21-11](https://user-images.githubusercontent.com/11317235/100901123-cd25b680-34c3-11eb-9543-b8e825fdfa67.png)

The same story for reading the menu-items
![Screenshot 2020-12-02 17-33-53](https://user-images.githubusercontent.com/11317235/100901910-a6b44b00-34c4-11eb-859a-761f2c60427d.png)

**Comment by ghost** [comment]
The duplicated queries for 'template' option and thumbnail models have been removed by introducing caching static properties to CZR_BASE.
The duplicated menu query is more complex to cache because the theme requests the same menu two times but with a different id.
A solution in the future would be to create a modified copy of wp_nav_menu().
