### ISSUE TITLE
Is Customizr compatible with learnpress ?

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#904]
https://wordpress.org/plugins/learnpress/

**Comment by ghost** [comment]
When you'll have time @eri-trabiccolo after v4

**Comment by ghost** [comment]
Another request for LearnPress

@eri-trabiccolo can you work on it ?

> Hello,
> 
> I've installed LearnPress and your Customizr Plugin (Customizr is really nice and efficient).
> 
> I've got some problems with Learnpress because i can't display the courses and lessons (courses and lessons work well). My website integrate WordPress 3.8 and the last version for customizr.
> 
> thanks by advance
> 
> 
> best regards
> 
> have you eared some difficulties with Learnpress ?

**Comment by eri-trabiccolo** [comment]
NO is not.
basically the opposite of the magic (blank page) happens because learnpress filters template_include, looks for its templates, whether they are defined in the theme, if not found it just assumes the theme has a page.php:
`$template = get_page_template();`

But Customizr doesn't have it.  So LP replaces the fall back on index.php with a fallback on any page-*.php, that we don't have => $template becomes "empty".
I don't think this is a good practice.

So, do we want to add the page.php template to make LP work?
Alternatively we need a compat code that checks if the LP included file exists otherwise fall back on index.php.
But honestly is something that the plugin shoud do: page.php is **not required**. 

Once this is done we have to add all our logic to make this page acting like an actual page and not like an archive etc etc.

Anyway:
working on it -> https://github.com/eri-trabiccolo/customizr/tree/lp-compat
