### ISSUE TITLE
TODO : following new file organization, check the following

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#907]
Following our work last friday

1. check if filter 'czr_get_ctx_excluded_options' is used in pro ?
2. check czr_fn_user_started_before_version in pro bundle? 
3. czr_fn_category_id_exists( in pro bundle ?
4. where do we use this filter  'czr_options_prefixes' ? WFC ? FPU ?

**Comment by eri-trabiccolo** [comment]
1. only in the bundle, fixed in https://github.com/presscustomizr/pro-bundle/tree/czr4-ready
2. wfc uses it in class_dyn_style, to print the menu item style first letter css. I propose to remove it.
It's valid only for customizr <= 3.4.33
3. yes, and it's fine
4. only in FC as said as the purpose of that filter is to be able to use options which do not start with tc_ in the customizer. -> fine
