### ISSUE TITLE
conflict with Newsletter Subscription Form plugin

### ISSUE THREAD

**Issue by giorgioriccardi** [Nikeo/customizr#965]
Hi all,
this plugin here: [https://it.wordpress.org/plugins/newsletter-subscription-form/](https://it.wordpress.org/plugins/newsletter-subscription-form/) (now removed from my site) is actually breaking Customizr Pro 1.3.8
I'm pretty sure it's their code that is overriding some of the js libraries of Czr.
The errors that is triggering are:
- doesn't display sliders (any)
- no featured images
- no sticky header
- no side menu available
- even overlapping admin wordpress toolbar on the header
Here is what it does: [http://www.awesomescreenshot.com/image/2590454/41d376ee915100c6ed993bec1dfb1f3b](http://www.awesomescreenshot.com/image/2590454/41d376ee915100c6ed993bec1dfb1f3b)
This is how it looks without that plugin: [https://cartup.it/](https://cartup.it/)
No need to address this, since the newsletter feature is quite useless for this project, but so you know there is still stuff out there interfering with your code.

Bests, 
Giorgio

**Comment by eri-trabiccolo** [comment]
Hi Giorgio ;),
thanks.
This is because that plugin replaces the WordPress jquery with an external one (via googleapis), preventing also the jquery-migrate enqueuing ( the latter is needed by some part of the theme js like for $.browser).

We'll see, but in this case I think is their "not very good" practice :D

Bests,
Rocco

**Comment by giorgioriccardi** [comment]
Rookies ;)
